/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyRevenue {
  'total' : bigint,
  'date' : string,
  'onlineAmount' : bigint,
  'cashAmount' : bigint,
}
export type FeesType = { 'cash' : null } |
  { 'online' : null };
export interface LibrarySettings {
  'totalSeats' : bigint,
  'address' : string,
  'openingHours' : string,
  'facilities' : Array<string>,
  'libraryName' : string,
  'phone' : string,
}
export interface Message {
  'id' : MessageId,
  'content' : string,
  'isRead' : boolean,
  'timestamp' : Timestamp,
  'senderName' : string,
  'senderRole' : SenderRole,
  'recipientId' : string,
  'senderId' : string,
}
export type MessageId = bigint;
export interface Notice {
  'id' : NoticeId,
  'title' : string,
  'content' : string,
  'createdAt' : Timestamp,
  'isActive' : boolean,
}
export type NoticeId = bigint;
export interface Quote { 'id' : QuoteId, 'quote' : string, 'author' : string }
export type QuoteId = bigint;
export interface RevenueByPaymentType {
  'cashTotal' : bigint,
  'grandTotal' : bigint,
  'onlineTotal' : bigint,
}
export interface Seat {
  'occupiedBy' : [] | [string],
  'isOccupied' : boolean,
  'seatNumber' : SeatNumber,
}
export type SeatNumber = bigint;
export type SenderRole = { 'admin' : null } |
  { 'student' : null };
export interface Student {
  'id' : StudentId,
  'feesType' : FeesType,
  'entryDate' : Timestamp,
  'studentId' : string,
  'feesAmount' : bigint,
  'expiryDate' : Timestamp,
  'name' : string,
  'isActive' : boolean,
  'fatherName' : string,
  'address' : string,
  'mobile' : string,
  'seatNumber' : SeatNumber,
}
export type StudentId = bigint;
export type Timestamp = bigint;
export interface _SERVICE {
  'addNotice' : ActorMethod<[string, string], Notice>,
  'addQuote' : ActorMethod<[string, string], Quote>,
  'addStudent' : ActorMethod<
    [
      string,
      string,
      SeatNumber,
      FeesType,
      bigint,
      Timestamp,
      string,
      string,
      string,
    ],
    Student
  >,
  'deleteNotice' : ActorMethod<[NoticeId], boolean>,
  'deleteQuote' : ActorMethod<[QuoteId], boolean>,
  'deleteStudent' : ActorMethod<[StudentId], boolean>,
  'getActiveNotices' : ActorMethod<[], Array<Notice>>,
  'getAllMessages' : ActorMethod<[], Array<Message>>,
  'getAllQuotes' : ActorMethod<[], Array<Quote>>,
  'getAllSeats' : ActorMethod<[], Array<Seat>>,
  'getAllStudents' : ActorMethod<[], Array<Student>>,
  'getAvailableSeats' : ActorMethod<[], Array<Seat>>,
  'getDailyRevenue' : ActorMethod<[string], DailyRevenue>,
  'getExpiredStudents' : ActorMethod<[], Array<Student>>,
  'getMessagesForStudent' : ActorMethod<[string], Array<Message>>,
  'getMonthlyRevenue' : ActorMethod<[bigint, bigint], bigint>,
  'getOccupiedSeats' : ActorMethod<[], Array<Seat>>,
  'getRandomQuote' : ActorMethod<[], [] | [Quote]>,
  'getRevenueByPaymentType' : ActorMethod<[], RevenueByPaymentType>,
  'getRevenueChart' : ActorMethod<[], Array<DailyRevenue>>,
  'getSeatStatus' : ActorMethod<[SeatNumber], [] | [Seat]>,
  'getSettings' : ActorMethod<[], LibrarySettings>,
  'getStudent' : ActorMethod<[StudentId], [] | [Student]>,
  'getStudentsExpiringSoon' : ActorMethod<[], Array<Student>>,
  'getTotalRevenue' : ActorMethod<[], bigint>,
  'getUnreadCount' : ActorMethod<[string], bigint>,
  'initializeSeats' : ActorMethod<[bigint], undefined>,
  'markMessageRead' : ActorMethod<[MessageId], boolean>,
  'searchStudents' : ActorMethod<[string], Array<Student>>,
  'sendBroadcast' : ActorMethod<[string], bigint>,
  'sendMessage' : ActorMethod<
    [string, string, SenderRole, string, string],
    Message
  >,
  'updateAdminCredentials' : ActorMethod<
    [string, string, string, string],
    boolean
  >,
  'updateNotice' : ActorMethod<[Notice], boolean>,
  'updateSeatOccupancy' : ActorMethod<
    [SeatNumber, boolean, [] | [string]],
    boolean
  >,
  'updateSettings' : ActorMethod<[LibrarySettings], undefined>,
  'updateStudent' : ActorMethod<[Student], boolean>,
  'verifyAdmin' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];