/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const NoticeId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Notice = IDL.Record({
  'id' : NoticeId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Timestamp,
  'isActive' : IDL.Bool,
});
export const QuoteId = IDL.Nat;
export const Quote = IDL.Record({
  'id' : QuoteId,
  'quote' : IDL.Text,
  'author' : IDL.Text,
});
export const SeatNumber = IDL.Nat;
export const FeesType = IDL.Variant({ 'cash' : IDL.Null, 'online' : IDL.Null });
export const StudentId = IDL.Nat;
export const Student = IDL.Record({
  'id' : StudentId,
  'feesType' : FeesType,
  'entryDate' : Timestamp,
  'studentId' : IDL.Text,
  'feesAmount' : IDL.Nat,
  'expiryDate' : Timestamp,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'fatherName' : IDL.Text,
  'address' : IDL.Text,
  'mobile' : IDL.Text,
  'seatNumber' : SeatNumber,
});
export const MessageId = IDL.Nat;
export const SenderRole = IDL.Variant({
  'admin' : IDL.Null,
  'student' : IDL.Null,
});
export const Message = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'isRead' : IDL.Bool,
  'timestamp' : Timestamp,
  'senderName' : IDL.Text,
  'senderRole' : SenderRole,
  'recipientId' : IDL.Text,
  'senderId' : IDL.Text,
});
export const Seat = IDL.Record({
  'occupiedBy' : IDL.Opt(IDL.Text),
  'isOccupied' : IDL.Bool,
  'seatNumber' : SeatNumber,
});
export const DailyRevenue = IDL.Record({
  'total' : IDL.Nat,
  'date' : IDL.Text,
  'onlineAmount' : IDL.Nat,
  'cashAmount' : IDL.Nat,
});
export const RevenueByPaymentType = IDL.Record({
  'cashTotal' : IDL.Nat,
  'grandTotal' : IDL.Nat,
  'onlineTotal' : IDL.Nat,
});
export const LibrarySettings = IDL.Record({
  'totalSeats' : IDL.Nat,
  'address' : IDL.Text,
  'openingHours' : IDL.Text,
  'facilities' : IDL.Vec(IDL.Text),
  'libraryName' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addNotice' : IDL.Func([IDL.Text, IDL.Text], [Notice], []),
  'addQuote' : IDL.Func([IDL.Text, IDL.Text], [Quote], []),
  'addStudent' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        SeatNumber,
        FeesType,
        IDL.Nat,
        Timestamp,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [Student],
      [],
    ),
  'deleteNotice' : IDL.Func([NoticeId], [IDL.Bool], []),
  'deleteQuote' : IDL.Func([QuoteId], [IDL.Bool], []),
  'deleteStudent' : IDL.Func([StudentId], [IDL.Bool], []),
  'getActiveNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
  'getAllMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getAllQuotes' : IDL.Func([], [IDL.Vec(Quote)], ['query']),
  'getAllSeats' : IDL.Func([], [IDL.Vec(Seat)], ['query']),
  'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getAvailableSeats' : IDL.Func([], [IDL.Vec(Seat)], ['query']),
  'getDailyRevenue' : IDL.Func([IDL.Text], [DailyRevenue], ['query']),
  'getExpiredStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getMessagesForStudent' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
  'getMonthlyRevenue' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], ['query']),
  'getOccupiedSeats' : IDL.Func([], [IDL.Vec(Seat)], ['query']),
  'getRandomQuote' : IDL.Func([], [IDL.Opt(Quote)], ['query']),
  'getRevenueByPaymentType' : IDL.Func([], [RevenueByPaymentType], ['query']),
  'getRevenueChart' : IDL.Func([], [IDL.Vec(DailyRevenue)], ['query']),
  'getSeatStatus' : IDL.Func([SeatNumber], [IDL.Opt(Seat)], ['query']),
  'getSettings' : IDL.Func([], [LibrarySettings], ['query']),
  'getStudent' : IDL.Func([StudentId], [IDL.Opt(Student)], ['query']),
  'getStudentsExpiringSoon' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getTotalRevenue' : IDL.Func([], [IDL.Nat], ['query']),
  'getUnreadCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'initializeSeats' : IDL.Func([IDL.Nat], [], []),
  'markMessageRead' : IDL.Func([MessageId], [IDL.Bool], []),
  'searchStudents' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
  'sendBroadcast' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'sendMessage' : IDL.Func(
      [IDL.Text, IDL.Text, SenderRole, IDL.Text, IDL.Text],
      [Message],
      [],
    ),
  'updateAdminCredentials' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateNotice' : IDL.Func([Notice], [IDL.Bool], []),
  'updateSeatOccupancy' : IDL.Func(
      [SeatNumber, IDL.Bool, IDL.Opt(IDL.Text)],
      [IDL.Bool],
      [],
    ),
  'updateSettings' : IDL.Func([LibrarySettings], [], []),
  'updateStudent' : IDL.Func([Student], [IDL.Bool], []),
  'verifyAdmin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const NoticeId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Notice = IDL.Record({
    'id' : NoticeId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Timestamp,
    'isActive' : IDL.Bool,
  });
  const QuoteId = IDL.Nat;
  const Quote = IDL.Record({
    'id' : QuoteId,
    'quote' : IDL.Text,
    'author' : IDL.Text,
  });
  const SeatNumber = IDL.Nat;
  const FeesType = IDL.Variant({ 'cash' : IDL.Null, 'online' : IDL.Null });
  const StudentId = IDL.Nat;
  const Student = IDL.Record({
    'id' : StudentId,
    'feesType' : FeesType,
    'entryDate' : Timestamp,
    'studentId' : IDL.Text,
    'feesAmount' : IDL.Nat,
    'expiryDate' : Timestamp,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'fatherName' : IDL.Text,
    'address' : IDL.Text,
    'mobile' : IDL.Text,
    'seatNumber' : SeatNumber,
  });
  const MessageId = IDL.Nat;
  const SenderRole = IDL.Variant({ 'admin' : IDL.Null, 'student' : IDL.Null });
  const Message = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'isRead' : IDL.Bool,
    'timestamp' : Timestamp,
    'senderName' : IDL.Text,
    'senderRole' : SenderRole,
    'recipientId' : IDL.Text,
    'senderId' : IDL.Text,
  });
  const Seat = IDL.Record({
    'occupiedBy' : IDL.Opt(IDL.Text),
    'isOccupied' : IDL.Bool,
    'seatNumber' : SeatNumber,
  });
  const DailyRevenue = IDL.Record({
    'total' : IDL.Nat,
    'date' : IDL.Text,
    'onlineAmount' : IDL.Nat,
    'cashAmount' : IDL.Nat,
  });
  const RevenueByPaymentType = IDL.Record({
    'cashTotal' : IDL.Nat,
    'grandTotal' : IDL.Nat,
    'onlineTotal' : IDL.Nat,
  });
  const LibrarySettings = IDL.Record({
    'totalSeats' : IDL.Nat,
    'address' : IDL.Text,
    'openingHours' : IDL.Text,
    'facilities' : IDL.Vec(IDL.Text),
    'libraryName' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'addNotice' : IDL.Func([IDL.Text, IDL.Text], [Notice], []),
    'addQuote' : IDL.Func([IDL.Text, IDL.Text], [Quote], []),
    'addStudent' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          SeatNumber,
          FeesType,
          IDL.Nat,
          Timestamp,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [Student],
        [],
      ),
    'deleteNotice' : IDL.Func([NoticeId], [IDL.Bool], []),
    'deleteQuote' : IDL.Func([QuoteId], [IDL.Bool], []),
    'deleteStudent' : IDL.Func([StudentId], [IDL.Bool], []),
    'getActiveNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
    'getAllMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getAllQuotes' : IDL.Func([], [IDL.Vec(Quote)], ['query']),
    'getAllSeats' : IDL.Func([], [IDL.Vec(Seat)], ['query']),
    'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getAvailableSeats' : IDL.Func([], [IDL.Vec(Seat)], ['query']),
    'getDailyRevenue' : IDL.Func([IDL.Text], [DailyRevenue], ['query']),
    'getExpiredStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getMessagesForStudent' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getMonthlyRevenue' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], ['query']),
    'getOccupiedSeats' : IDL.Func([], [IDL.Vec(Seat)], ['query']),
    'getRandomQuote' : IDL.Func([], [IDL.Opt(Quote)], ['query']),
    'getRevenueByPaymentType' : IDL.Func([], [RevenueByPaymentType], ['query']),
    'getRevenueChart' : IDL.Func([], [IDL.Vec(DailyRevenue)], ['query']),
    'getSeatStatus' : IDL.Func([SeatNumber], [IDL.Opt(Seat)], ['query']),
    'getSettings' : IDL.Func([], [LibrarySettings], ['query']),
    'getStudent' : IDL.Func([StudentId], [IDL.Opt(Student)], ['query']),
    'getStudentsExpiringSoon' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getTotalRevenue' : IDL.Func([], [IDL.Nat], ['query']),
    'getUnreadCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'initializeSeats' : IDL.Func([IDL.Nat], [], []),
    'markMessageRead' : IDL.Func([MessageId], [IDL.Bool], []),
    'searchStudents' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
    'sendBroadcast' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'sendMessage' : IDL.Func(
        [IDL.Text, IDL.Text, SenderRole, IDL.Text, IDL.Text],
        [Message],
        [],
      ),
    'updateAdminCredentials' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateNotice' : IDL.Func([Notice], [IDL.Bool], []),
    'updateSeatOccupancy' : IDL.Func(
        [SeatNumber, IDL.Bool, IDL.Opt(IDL.Text)],
        [IDL.Bool],
        [],
      ),
    'updateSettings' : IDL.Func([LibrarySettings], [], []),
    'updateStudent' : IDL.Func([Student], [IDL.Bool], []),
    'verifyAdmin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };