/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LibrarySettings {
    totalSeats: bigint;
    address: string;
    openingHours: string;
    facilities: Array<string>;
    libraryName: string;
    phone: string;
}
export type Timestamp = bigint;
export interface Seat {
    occupiedBy?: string;
    isOccupied: boolean;
    seatNumber: SeatNumber;
}
export type StudentId = bigint;
export interface DailyRevenue {
    total: bigint;
    date: string;
    onlineAmount: bigint;
    cashAmount: bigint;
}
export type QuoteId = bigint;
export type SeatNumber = bigint;
export type MessageId = bigint;
export interface Notice {
    id: NoticeId;
    title: string;
    content: string;
    createdAt: Timestamp;
    isActive: boolean;
}
export interface Message {
    id: MessageId;
    content: string;
    isRead: boolean;
    timestamp: Timestamp;
    senderName: string;
    senderRole: SenderRole;
    recipientId: string;
    senderId: string;
}
export interface RevenueByPaymentType {
    cashTotal: bigint;
    grandTotal: bigint;
    onlineTotal: bigint;
}
export interface Quote {
    id: QuoteId;
    quote: string;
    author: string;
}
export type NoticeId = bigint;
export interface Student {
    id: StudentId;
    feesType: FeesType;
    entryDate: Timestamp;
    studentId: string;
    feesAmount: bigint;
    expiryDate: Timestamp;
    name: string;
    isActive: boolean;
    fatherName: string;
    address: string;
    mobile: string;
    seatNumber: SeatNumber;
}
export enum FeesType {
    cash = "cash",
    online = "online"
}
export enum SenderRole {
    admin = "admin",
    student = "student"
}
export interface backendInterface {
    addNotice(title: string, content: string): Promise<Notice>;
    addQuote(text: string, author: string): Promise<Quote>;
    addStudent(name: string, mobile: string, seatNumber: SeatNumber, feesType: FeesType, feesAmount: bigint, entryDate: Timestamp, address: string, fatherName: string, studentId: string): Promise<Student>;
    deleteNotice(id: NoticeId): Promise<boolean>;
    deleteQuote(id: QuoteId): Promise<boolean>;
    deleteStudent(id: StudentId): Promise<boolean>;
    getActiveNotices(): Promise<Array<Notice>>;
    getAllMessages(): Promise<Array<Message>>;
    getAllQuotes(): Promise<Array<Quote>>;
    getAllSeats(): Promise<Array<Seat>>;
    getAllStudents(): Promise<Array<Student>>;
    getAvailableSeats(): Promise<Array<Seat>>;
    getDailyRevenue(date: string): Promise<DailyRevenue>;
    getExpiredStudents(): Promise<Array<Student>>;
    getMessagesForStudent(studentId: string): Promise<Array<Message>>;
    getMonthlyRevenue(year: bigint, month: bigint): Promise<bigint>;
    getOccupiedSeats(): Promise<Array<Seat>>;
    getRandomQuote(): Promise<Quote | null>;
    getRevenueByPaymentType(): Promise<RevenueByPaymentType>;
    getRevenueChart(): Promise<Array<DailyRevenue>>;
    getSeatStatus(seatNumber: SeatNumber): Promise<Seat | null>;
    getSettings(): Promise<LibrarySettings>;
    getStudent(id: StudentId): Promise<Student | null>;
    getStudentsExpiringSoon(): Promise<Array<Student>>;
    getTotalRevenue(): Promise<bigint>;
    getUnreadCount(recipientId: string): Promise<bigint>;
    initializeSeats(totalSeats: bigint): Promise<void>;
    markMessageRead(id: MessageId): Promise<boolean>;
    searchStudents(term: string): Promise<Array<Student>>;
    sendBroadcast(content: string): Promise<bigint>;
    sendMessage(senderId: string, senderName: string, senderRole: SenderRole, recipientId: string, content: string): Promise<Message>;
    updateAdminCredentials(currentPassword: string, newUsername: string, newEmail: string, newPassword: string): Promise<boolean>;
    updateNotice(updated: Notice): Promise<boolean>;
    updateSeatOccupancy(seatNumber: SeatNumber, isOccupied: boolean, occupiedBy: string | null): Promise<boolean>;
    updateSettings(updated: LibrarySettings): Promise<void>;
    updateStudent(updated: Student): Promise<boolean>;
    verifyAdmin(username: string, password: string): Promise<boolean>;
}
import type { FeesType as _FeesType, Message as _Message, MessageId as _MessageId, Quote as _Quote, Seat as _Seat, SeatNumber as _SeatNumber, SenderRole as _SenderRole, Student as _Student, StudentId as _StudentId, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addNotice(arg0: string, arg1: string): Promise<Notice> {
        if (this.processError) {
            try {
                const result = await this.actor.addNotice(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNotice(arg0, arg1);
            return result;
        }
    }
    async addQuote(arg0: string, arg1: string): Promise<Quote> {
        if (this.processError) {
            try {
                const result = await this.actor.addQuote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addQuote(arg0, arg1);
            return result;
        }
    }
    async addStudent(arg0: string, arg1: string, arg2: SeatNumber, arg3: FeesType, arg4: bigint, arg5: Timestamp, arg6: string, arg7: string, arg8: string): Promise<Student> {
        if (this.processError) {
            try {
                const result = await this.actor.addStudent(arg0, arg1, arg2, to_candid_FeesType_n1(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, arg8);
                return from_candid_Student_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStudent(arg0, arg1, arg2, to_candid_FeesType_n1(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, arg8);
            return from_candid_Student_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteNotice(arg0: NoticeId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNotice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNotice(arg0);
            return result;
        }
    }
    async deleteQuote(arg0: QuoteId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteQuote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteQuote(arg0);
            return result;
        }
    }
    async deleteStudent(arg0: StudentId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudent(arg0);
            return result;
        }
    }
    async getActiveNotices(): Promise<Array<Notice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveNotices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveNotices();
            return result;
        }
    }
    async getAllMessages(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMessages();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMessages();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllQuotes(): Promise<Array<Quote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllQuotes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllQuotes();
            return result;
        }
    }
    async getAllSeats(): Promise<Array<Seat>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSeats();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSeats();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllStudents(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudents();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudents();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableSeats(): Promise<Array<Seat>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableSeats();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableSeats();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyRevenue(arg0: string): Promise<DailyRevenue> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyRevenue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyRevenue(arg0);
            return result;
        }
    }
    async getExpiredStudents(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpiredStudents();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpiredStudents();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessagesForStudent(arg0: string): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessagesForStudent(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessagesForStudent(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMonthlyRevenue(arg0: bigint, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyRevenue(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyRevenue(arg0, arg1);
            return result;
        }
    }
    async getOccupiedSeats(): Promise<Array<Seat>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOccupiedSeats();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOccupiedSeats();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRandomQuote(): Promise<Quote | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRandomQuote();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRandomQuote();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRevenueByPaymentType(): Promise<RevenueByPaymentType> {
        if (this.processError) {
            try {
                const result = await this.actor.getRevenueByPaymentType();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRevenueByPaymentType();
            return result;
        }
    }
    async getRevenueChart(): Promise<Array<DailyRevenue>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRevenueChart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRevenueChart();
            return result;
        }
    }
    async getSeatStatus(arg0: SeatNumber): Promise<Seat | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSeatStatus(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSeatStatus(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSettings(): Promise<LibrarySettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return result;
        }
    }
    async getStudent(arg0: StudentId): Promise<Student | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudent(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudent(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentsExpiringSoon(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentsExpiringSoon();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentsExpiringSoon();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalRevenue(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalRevenue();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalRevenue();
            return result;
        }
    }
    async getUnreadCount(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadCount(arg0);
            return result;
        }
    }
    async initializeSeats(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeSeats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeSeats(arg0);
            return result;
        }
    }
    async markMessageRead(arg0: MessageId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markMessageRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markMessageRead(arg0);
            return result;
        }
    }
    async searchStudents(arg0: string): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchStudents(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchStudents(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendBroadcast(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.sendBroadcast(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendBroadcast(arg0);
            return result;
        }
    }
    async sendMessage(arg0: string, arg1: string, arg2: SenderRole, arg3: string, arg4: string): Promise<Message> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1, to_candid_SenderRole_n20(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return from_candid_Message_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1, to_candid_SenderRole_n20(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return from_candid_Message_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateAdminCredentials(arg0: string, arg1: string, arg2: string, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAdminCredentials(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAdminCredentials(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateNotice(arg0: Notice): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNotice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNotice(arg0);
            return result;
        }
    }
    async updateSeatOccupancy(arg0: SeatNumber, arg1: boolean, arg2: string | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSeatOccupancy(arg0, arg1, to_candid_opt_n22(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSeatOccupancy(arg0, arg1, to_candid_opt_n22(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateSettings(arg0: LibrarySettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSettings(arg0);
            return result;
        }
    }
    async updateStudent(arg0: Student): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudent(to_candid_Student_n23(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudent(to_candid_Student_n23(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async verifyAdmin(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAdmin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAdmin(arg0, arg1);
            return result;
        }
    }
}
function from_candid_FeesType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeesType): FeesType {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Message_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Message): Message {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Seat_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Seat): Seat {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_SenderRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SenderRole): SenderRole {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Student_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Student): Student {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Quote]): Quote | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Seat]): Seat | null {
    return value.length === 0 ? null : from_candid_Seat_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Student]): Student | null {
    return value.length === 0 ? null : from_candid_Student_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    occupiedBy: [] | [string];
    isOccupied: boolean;
    seatNumber: _SeatNumber;
}): {
    occupiedBy?: string;
    isOccupied: boolean;
    seatNumber: SeatNumber;
} {
    return {
        occupiedBy: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.occupiedBy)),
        isOccupied: value.isOccupied,
        seatNumber: value.seatNumber
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _StudentId;
    feesType: _FeesType;
    entryDate: _Timestamp;
    studentId: string;
    feesAmount: bigint;
    expiryDate: _Timestamp;
    name: string;
    isActive: boolean;
    fatherName: string;
    address: string;
    mobile: string;
    seatNumber: _SeatNumber;
}): {
    id: StudentId;
    feesType: FeesType;
    entryDate: Timestamp;
    studentId: string;
    feesAmount: bigint;
    expiryDate: Timestamp;
    name: string;
    isActive: boolean;
    fatherName: string;
    address: string;
    mobile: string;
    seatNumber: SeatNumber;
} {
    return {
        id: value.id,
        feesType: from_candid_FeesType_n5(_uploadFile, _downloadFile, value.feesType),
        entryDate: value.entryDate,
        studentId: value.studentId,
        feesAmount: value.feesAmount,
        expiryDate: value.expiryDate,
        name: value.name,
        isActive: value.isActive,
        fatherName: value.fatherName,
        address: value.address,
        mobile: value.mobile,
        seatNumber: value.seatNumber
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MessageId;
    content: string;
    isRead: boolean;
    timestamp: _Timestamp;
    senderName: string;
    senderRole: _SenderRole;
    recipientId: string;
    senderId: string;
}): {
    id: MessageId;
    content: string;
    isRead: boolean;
    timestamp: Timestamp;
    senderName: string;
    senderRole: SenderRole;
    recipientId: string;
    senderId: string;
} {
    return {
        id: value.id,
        content: value.content,
        isRead: value.isRead,
        timestamp: value.timestamp,
        senderName: value.senderName,
        senderRole: from_candid_SenderRole_n10(_uploadFile, _downloadFile, value.senderRole),
        recipientId: value.recipientId,
        senderId: value.senderId
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    student: null;
}): SenderRole {
    return "admin" in value ? SenderRole.admin : "student" in value ? SenderRole.student : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cash: null;
} | {
    online: null;
}): FeesType {
    return "cash" in value ? FeesType.cash : "online" in value ? FeesType.online : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Seat>): Array<Seat> {
    return value.map((x)=>from_candid_Seat_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Student>): Array<Student> {
    return value.map((x)=>from_candid_Student_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Message>): Array<Message> {
    return value.map((x)=>from_candid_Message_n8(_uploadFile, _downloadFile, x));
}
function to_candid_FeesType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FeesType): _FeesType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_SenderRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SenderRole): _SenderRole {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_Student_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Student): _Student {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: StudentId;
    feesType: FeesType;
    entryDate: Timestamp;
    studentId: string;
    feesAmount: bigint;
    expiryDate: Timestamp;
    name: string;
    isActive: boolean;
    fatherName: string;
    address: string;
    mobile: string;
    seatNumber: SeatNumber;
}): {
    id: _StudentId;
    feesType: _FeesType;
    entryDate: _Timestamp;
    studentId: string;
    feesAmount: bigint;
    expiryDate: _Timestamp;
    name: string;
    isActive: boolean;
    fatherName: string;
    address: string;
    mobile: string;
    seatNumber: _SeatNumber;
} {
    return {
        id: value.id,
        feesType: to_candid_FeesType_n1(_uploadFile, _downloadFile, value.feesType),
        entryDate: value.entryDate,
        studentId: value.studentId,
        feesAmount: value.feesAmount,
        expiryDate: value.expiryDate,
        name: value.name,
        isActive: value.isActive,
        fatherName: value.fatherName,
        address: value.address,
        mobile: value.mobile,
        seatNumber: value.seatNumber
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FeesType): {
    cash: null;
} | {
    online: null;
} {
    return value == FeesType.cash ? {
        cash: null
    } : value == FeesType.online ? {
        online: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SenderRole): {
    admin: null;
} | {
    student: null;
} {
    return value == SenderRole.admin ? {
        admin: null
    } : value == SenderRole.student ? {
        student: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
